import type { Metadata } from 'next'
import './globals.css'
import NextAuthSessionProvider from './_providers/sessionProvider'
import { Toaster } from '@/components/ui/sonner'
import ReactQueryProvider from './_providers/reactQueryProvider'

export const metadata: Metadata = {
  title: 'IAGENTE CHALLENGE',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ReactQueryProvider>
          <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
        </ReactQueryProvider>
        <Toaster />
      </body>
    </html>
  )
}
